"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$nodejs\
[](fg:#86BBD8 bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

[username]
disabled    = false
format      = '[Stellaris Stats Devcontainer  ]($style)'
show_always = true
style_root  = "bg:#9A348E"
style_user  = "bg:#9A348E"

[directory]
format            = "[ $path ]($style)"
style             = "bg:#DA627D"
truncate_to_repo  = true
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
format = '[ $symbol $branch ]($style)'
style  = "bg:#FCA17D"
symbol = ""

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style  = "bg:#FCA17D"

[nodejs]
format = '[ $symbol ($version) ]($style)'
style  = "bg:#86BBD8"
symbol = ""

[time]
disabled    = false
format      = '[ $time ]($style)'
style       = "bg:#33658A"
time_format = "%R"
