"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$nodejs\
[](fg:#86BBD8 bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

[username]
show_always = true
style_user  = "bg:#9A348E"
style_root  = "bg:#9A348E"
format      = '[Stellaris Stats Devcontainer  ]($style)'
disabled    = false

[directory]
style             = "bg:#DA627D"
format            = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo  = true

[git_branch]
symbol = ""
style  = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style  = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style  = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled    = false
time_format = "%R"
style       = "bg:#33658A"
format      = '[ $time ]($style)'